# Generated by Django 4.2 on 2023-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blog',
            field=models.ManyToManyField(related_name='tags', to='blog.blog'),
        ),
    ]
